//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 07:42:22 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExplicitWizardMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExplicitWizardMetadata">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.thedocumentwizard.nl/wizardconfiguration/2.0>WizardMetadata">
 *       &lt;attribute name="metadataID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="metadataName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExplicitWizardMetadata")
public class ExplicitWizardMetadata
    extends WizardMetadata
{

    @XmlAttribute(name = "metadataID")
    protected String metadataID;
    @XmlAttribute(name = "metadataName")
    protected String metadataName;

    /**
     * Gets the value of the metadataID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataID() {
        return metadataID;
    }

    /**
     * Sets the value of the metadataID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataID(String value) {
        this.metadataID = value;
    }

    /**
     * Gets the value of the metadataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataName() {
        return metadataName;
    }

    /**
     * Sets the value of the metadataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataName(String value) {
        this.metadataName = value;
    }

}
