//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 07:42:22 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Value" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ExplicitWizardMetadata" minOccurs="0"/>
 *         &lt;element name="DisplayText" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ExplicitWizardMetadata" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListItem", propOrder = {
    "value",
    "displayText"
})
public class ListItem {

    @XmlElement(name = "Value")
    protected ExplicitWizardMetadata value;
    @XmlElement(name = "DisplayText")
    protected ExplicitWizardMetadata displayText;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ExplicitWizardMetadata }
     *     
     */
    public ExplicitWizardMetadata getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplicitWizardMetadata }
     *     
     */
    public void setValue(ExplicitWizardMetadata value) {
        this.value = value;
    }

    /**
     * Gets the value of the displayText property.
     * 
     * @return
     *     possible object is
     *     {@link ExplicitWizardMetadata }
     *     
     */
    public ExplicitWizardMetadata getDisplayText() {
        return displayText;
    }

    /**
     * Sets the value of the displayText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplicitWizardMetadata }
     *     
     */
    public void setDisplayText(ExplicitWizardMetadata value) {
        this.displayText = value;
    }

}
