//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 07:42:22 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumberControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumberControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}AbstractControl">
 *       &lt;attribute name="allowDecimals" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="decimalPrecision" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="decimalSeparator" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}Separator" />
 *       &lt;attribute name="minValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="maxValue" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="trimTrailedZeros" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="outputFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="trailingZerosReplacement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberControl")
public class NumberControl
    extends AbstractControl
{

    @XmlAttribute(name = "allowDecimals")
    protected Boolean allowDecimals;
    @XmlAttribute(name = "decimalPrecision")
    protected Integer decimalPrecision;
    @XmlAttribute(name = "decimalSeparator")
    protected Separator decimalSeparator;
    @XmlAttribute(name = "minValue")
    protected Float minValue;
    @XmlAttribute(name = "maxValue")
    protected Float maxValue;
    @XmlAttribute(name = "trimTrailedZeros")
    protected Boolean trimTrailedZeros;
    @XmlAttribute(name = "outputFormat")
    protected String outputFormat;
    @XmlAttribute(name = "trailingZerosReplacement")
    protected String trailingZerosReplacement;
    @XmlAttribute(name = "step")
    protected Float step;

    /**
     * Gets the value of the allowDecimals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowDecimals() {
        return allowDecimals;
    }

    /**
     * Sets the value of the allowDecimals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDecimals(Boolean value) {
        this.allowDecimals = value;
    }

    /**
     * Gets the value of the decimalPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDecimalPrecision() {
        return decimalPrecision;
    }

    /**
     * Sets the value of the decimalPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDecimalPrecision(Integer value) {
        this.decimalPrecision = value;
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link Separator }
     *     
     */
    public Separator getDecimalSeparator() {
        return decimalSeparator;
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Separator }
     *     
     */
    public void setDecimalSeparator(Separator value) {
        this.decimalSeparator = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinValue(Float value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaxValue(Float value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the trimTrailedZeros property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrimTrailedZeros() {
        return trimTrailedZeros;
    }

    /**
     * Sets the value of the trimTrailedZeros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrimTrailedZeros(Boolean value) {
        this.trimTrailedZeros = value;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the trailingZerosReplacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailingZerosReplacement() {
        return trailingZerosReplacement;
    }

    /**
     * Sets the value of the trailingZerosReplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailingZerosReplacement(String value) {
        this.trailingZerosReplacement = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStep(Float value) {
        this.step = value;
    }

}
