//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 03:56:41 PM CEST 
//


package nl.thedocumentwizard.wizardconfiguration.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScriptType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScriptType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EnterStep"/>
 *     &lt;enumeration value="ExitStep"/>
 *     &lt;enumeration value="Validation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScriptType")
@XmlEnum
public enum ScriptType {

    @XmlEnumValue("EnterStep")
    ENTER_STEP("EnterStep"),
    @XmlEnumValue("ExitStep")
    EXIT_STEP("ExitStep"),
    @XmlEnumValue("Validation")
    VALIDATION("Validation");
    private final String value;

    ScriptType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScriptType fromValue(String v) {
        for (ScriptType c: ScriptType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
