//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 07:42:22 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for steptype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="steptype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Conditions" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ArrayOfWizardCondition" minOccurs="0"/>
 *         &lt;element name="AdvancedRules" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ArrayOfWizardAdvancedRule" minOccurs="0"/>
 *         &lt;element name="Questions" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ArrayOfWizardQuestion" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="START"/>
 *             &lt;enumeration value="STEP"/>
 *             &lt;enumeration value="FINISH"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nextStepID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "steptype", propOrder = {
    "conditions",
    "advancedRules",
    "questions"
})
public class Steptype {

    @XmlElement(name = "Conditions")
    protected ArrayOfWizardCondition conditions;
    @XmlElement(name = "AdvancedRules")
    protected ArrayOfWizardAdvancedRule advancedRules;
    @XmlElement(name = "Questions")
    protected ArrayOfWizardQuestion questions;
    @XmlAttribute(name = "id", required = true)
    protected int id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "groupName")
    protected String groupName;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "nextStepID")
    protected Integer nextStepID;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWizardCondition }
     *     
     */
    public ArrayOfWizardCondition getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWizardCondition }
     *     
     */
    public void setConditions(ArrayOfWizardCondition value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the advancedRules property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWizardAdvancedRule }
     *     
     */
    public ArrayOfWizardAdvancedRule getAdvancedRules() {
        return advancedRules;
    }

    /**
     * Sets the value of the advancedRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWizardAdvancedRule }
     *     
     */
    public void setAdvancedRules(ArrayOfWizardAdvancedRule value) {
        this.advancedRules = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWizardQuestion }
     *     
     */
    public ArrayOfWizardQuestion getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWizardQuestion }
     *     
     */
    public void setQuestions(ArrayOfWizardQuestion value) {
        this.questions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the nextStepID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNextStepID() {
        return nextStepID;
    }

    /**
     * Sets the value of the nextStepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNextStepID(Integer value) {
        this.nextStepID = value;
    }

}
