//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:49:39 AM CET 
//


package com.streamserve.schemas.documenttype._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Represents one document type.
 * 			
 * 
 * <p>Java class for DocumentTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadataTypes" type="{http://schemas.streamserve.com/documenttype/1.0}MetadataTypesType" minOccurs="0"/>
 *         &lt;element name="samples" type="{http://schemas.streamserve.com/documenttype/1.0}SamplesType" minOccurs="0"/>
 *         &lt;element name="metadataGroup" type="{http://schemas.streamserve.com/documenttype/1.0}MetadataGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="guid" use="required" type="{http://schemas.streamserve.com/public/1.0}GUIDType" />
 *       &lt;attribute name="revision" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentTypeType", propOrder = {
    "metadataTypes",
    "samples",
    "metadataGroup"
})
public class DocumentTypeType {

    protected MetadataTypesType metadataTypes;
    protected SamplesType samples;
    protected List<MetadataGroupType> metadataGroup;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "guid", required = true)
    protected String guid;
    @XmlAttribute(name = "revision", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long revision;

    /**
     * Gets the value of the metadataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataTypesType }
     *     
     */
    public MetadataTypesType getMetadataTypes() {
        return metadataTypes;
    }

    /**
     * Sets the value of the metadataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataTypesType }
     *     
     */
    public void setMetadataTypes(MetadataTypesType value) {
        this.metadataTypes = value;
    }

    /**
     * Gets the value of the samples property.
     * 
     * @return
     *     possible object is
     *     {@link SamplesType }
     *     
     */
    public SamplesType getSamples() {
        return samples;
    }

    /**
     * Sets the value of the samples property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplesType }
     *     
     */
    public void setSamples(SamplesType value) {
        this.samples = value;
    }

    /**
     * Gets the value of the metadataGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataGroupType }
     * 
     * 
     */
    public List<MetadataGroupType> getMetadataGroup() {
        if (metadataGroup == null) {
            metadataGroup = new ArrayList<MetadataGroupType>();
        }
        return this.metadataGroup;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     */
    public long getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     */
    public void setRevision(long value) {
        this.revision = value;
    }

}
