//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:49:39 AM CET 
//


package com.streamserve.schemas.documenttype._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.streamserve.schemas.documenttype._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.streamserve.schemas.documenttype._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetadataTypesType }
     * 
     */
    public MetadataTypesType createMetadataTypesType() {
        return new MetadataTypesType();
    }

    /**
     * Create an instance of {@link SamplesType }
     * 
     */
    public SamplesType createSamplesType() {
        return new SamplesType();
    }

    /**
     * Create an instance of {@link Strs }
     * 
     */
    public Strs createStrs() {
        return new Strs();
    }

    /**
     * Create an instance of {@link DocumentTypes }
     * 
     */
    public DocumentTypes createDocumentTypes() {
        return new DocumentTypes();
    }

    /**
     * Create an instance of {@link DocumentTypeType }
     * 
     */
    public DocumentTypeType createDocumentTypeType() {
        return new DocumentTypeType();
    }

    /**
     * Create an instance of {@link MetadataGroupType }
     * 
     */
    public MetadataGroupType createMetadataGroupType() {
        return new MetadataGroupType();
    }

    /**
     * Create an instance of {@link MetadataTypesType.Metadata }
     * 
     */
    public MetadataTypesType.Metadata createMetadataTypesTypeMetadata() {
        return new MetadataTypesType.Metadata();
    }

    /**
     * Create an instance of {@link SamplesType.Sample }
     * 
     */
    public SamplesType.Sample createSamplesTypeSample() {
        return new SamplesType.Sample();
    }

}
