//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:49:39 AM CET 
//


package com.streamserve.schemas._public._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ID"/>
 *     &lt;enumeration value="Type"/>
 *     &lt;enumeration value="Name"/>
 *     &lt;enumeration value="Description"/>
 *     &lt;enumeration value="Version"/>
 *     &lt;enumeration value="Revision"/>
 *     &lt;enumeration value="CreationTime"/>
 *     &lt;enumeration value="ModifyTime"/>
 *     &lt;enumeration value="ExpiringTime"/>
 *     &lt;enumeration value="State"/>
 *     &lt;enumeration value="ServiceName"/>
 *     &lt;enumeration value="RuleName"/>
 *     &lt;enumeration value="RuleID"/>
 *     &lt;enumeration value="Comment"/>
 *     &lt;enumeration value="ErrorCode"/>
 *     &lt;enumeration value="ErrorMessage"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Shared"/>
 *     &lt;enumeration value="AdhocEnabled"/>
 *     &lt;enumeration value="TypeName"/>
 *     &lt;enumeration value="ExternalID"/>
 *     &lt;enumeration value="TemplateName"/>
 *     &lt;enumeration value="DocumentTypeID"/>
 *     &lt;enumeration value="ServiceVersion"/>
 *     &lt;enumeration value="DocumentAbstractionID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttributeEnumType")
@XmlEnum
public enum AttributeEnumType {

    ID("ID"),
    @XmlEnumValue("Type")
    TYPE("Type"),
    @XmlEnumValue("Name")
    NAME("Name"),
    @XmlEnumValue("Description")
    DESCRIPTION("Description"),
    @XmlEnumValue("Version")
    VERSION("Version"),
    @XmlEnumValue("Revision")
    REVISION("Revision"),
    @XmlEnumValue("CreationTime")
    CREATION_TIME("CreationTime"),
    @XmlEnumValue("ModifyTime")
    MODIFY_TIME("ModifyTime"),
    @XmlEnumValue("ExpiringTime")
    EXPIRING_TIME("ExpiringTime"),
    @XmlEnumValue("State")
    STATE("State"),
    @XmlEnumValue("ServiceName")
    SERVICE_NAME("ServiceName"),
    @XmlEnumValue("RuleName")
    RULE_NAME("RuleName"),
    @XmlEnumValue("RuleID")
    RULE_ID("RuleID"),
    @XmlEnumValue("Comment")
    COMMENT("Comment"),
    @XmlEnumValue("ErrorCode")
    ERROR_CODE("ErrorCode"),
    @XmlEnumValue("ErrorMessage")
    ERROR_MESSAGE("ErrorMessage"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("Shared")
    SHARED("Shared"),
    @XmlEnumValue("AdhocEnabled")
    ADHOC_ENABLED("AdhocEnabled"),
    @XmlEnumValue("TypeName")
    TYPE_NAME("TypeName"),
    @XmlEnumValue("ExternalID")
    EXTERNAL_ID("ExternalID"),
    @XmlEnumValue("TemplateName")
    TEMPLATE_NAME("TemplateName"),
    @XmlEnumValue("DocumentTypeID")
    DOCUMENT_TYPE_ID("DocumentTypeID"),
    @XmlEnumValue("ServiceVersion")
    SERVICE_VERSION("ServiceVersion"),
    @XmlEnumValue("DocumentAbstractionID")
    DOCUMENT_ABSTRACTION_ID("DocumentAbstractionID");
    private final String value;

    AttributeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttributeEnumType fromValue(String v) {
        for (AttributeEnumType c: AttributeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
