//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 06:05:10 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfChoice2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfChoice2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Text" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}TextControl"/>
 *         &lt;element name="Number" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}NumberControl"/>
 *         &lt;element name="Attachment" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}AttachmentFileControl"/>
 *         &lt;element name="Label" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}LabelControl"/>
 *         &lt;element name="String" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}StringControl"/>
 *         &lt;element name="Date" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}DateControl"/>
 *         &lt;element name="Email" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}EmailControl"/>
 *         &lt;element name="Image" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ImageFileControl"/>
 *         &lt;element name="Checkbox" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}CheckboxControl"/>
 *         &lt;element name="Radio" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}RadioControl"/>
 *         &lt;element name="List" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ListControl"/>
 *         &lt;element name="Multi" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}MultiControl"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfChoice2", propOrder = {
    "textOrNumberOrAttachment"
})
public class ArrayOfChoice2 {

    @XmlElements({
        @XmlElement(name = "Text", type = TextControl.class, nillable = true),
        @XmlElement(name = "Number", type = NumberControl.class, nillable = true),
        @XmlElement(name = "Attachment", type = AttachmentFileControl.class, nillable = true),
        @XmlElement(name = "Label", type = LabelControl.class, nillable = true),
        @XmlElement(name = "String", type = StringControl.class, nillable = true),
        @XmlElement(name = "Date", type = DateControl.class, nillable = true),
        @XmlElement(name = "Email", type = EmailControl.class, nillable = true),
        @XmlElement(name = "Image", type = ImageFileControl.class, nillable = true),
        @XmlElement(name = "Checkbox", type = CheckboxControl.class, nillable = true),
        @XmlElement(name = "Radio", type = RadioControl.class, nillable = true),
        @XmlElement(name = "List", type = ListControl.class, nillable = true),
        @XmlElement(name = "Multi", type = MultiControl.class, nillable = true)
    })
    protected List<AbstractControl> textOrNumberOrAttachment;

    /**
     * Gets the value of the textOrNumberOrAttachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textOrNumberOrAttachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextOrNumberOrAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextControl }
     * {@link NumberControl }
     * {@link AttachmentFileControl }
     * {@link LabelControl }
     * {@link StringControl }
     * {@link DateControl }
     * {@link EmailControl }
     * {@link ImageFileControl }
     * {@link CheckboxControl }
     * {@link RadioControl }
     * {@link ListControl }
     * {@link MultiControl }
     * 
     * 
     */
    public List<AbstractControl> getTextOrNumberOrAttachment() {
        if (textOrNumberOrAttachment == null) {
            textOrNumberOrAttachment = new ArrayList<AbstractControl>();
        }
        return this.textOrNumberOrAttachment;
    }

}
