//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 06:05:10 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileNameControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileNameControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}StringControl">
 *       &lt;sequence>
 *         &lt;element name="ParentControl" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}FileControl" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileNameControl", propOrder = {
    "parentControl"
})
public class FileNameControl
    extends StringControl
{

    @XmlElement(name = "ParentControl")
    protected FileControl parentControl;

    /**
     * Gets the value of the parentControl property.
     * 
     * @return
     *     possible object is
     *     {@link FileControl }
     *     
     */
    public FileControl getParentControl() {
        return parentControl;
    }

    /**
     * Sets the value of the parentControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileControl }
     *     
     */
    public void setParentControl(FileControl value) {
        this.parentControl = value;
    }

}
