//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 06:05:10 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}AbstractControl">
 *       &lt;sequence>
 *         &lt;element name="XPath" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}XPathDataSource" minOccurs="0"/>
 *         &lt;element name="Items" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ArrayOfListItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListControl", propOrder = {
    "xPath",
    "items"
})
public class ListControl
    extends AbstractControl
{

    @XmlElement(name = "XPath")
    protected XPathDataSource xPath;
    @XmlElement(name = "Items")
    protected ArrayOfListItem items;

    /**
     * Gets the value of the xPath property.
     * 
     * @return
     *     possible object is
     *     {@link XPathDataSource }
     *     
     */
    public XPathDataSource getXPath() {
        return xPath;
    }

    /**
     * Sets the value of the xPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link XPathDataSource }
     *     
     */
    public void setXPath(XPathDataSource value) {
        this.xPath = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfListItem }
     *     
     */
    public ArrayOfListItem getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfListItem }
     *     
     */
    public void setItems(ArrayOfListItem value) {
        this.items = value;
    }

}
