//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 06:05:10 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.thedocumentwizard.wizardconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.thedocumentwizard.wizardconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfWizardCondition }
     * 
     */
    public ArrayOfWizardCondition createArrayOfWizardCondition() {
        return new ArrayOfWizardCondition();
    }

    /**
     * Create an instance of {@link ArrayOfWizardAdvancedRule }
     * 
     */
    public ArrayOfWizardAdvancedRule createArrayOfWizardAdvancedRule() {
        return new ArrayOfWizardAdvancedRule();
    }

    /**
     * Create an instance of {@link ArrayOfWizardQuestion }
     * 
     */
    public ArrayOfWizardQuestion createArrayOfWizardQuestion() {
        return new ArrayOfWizardQuestion();
    }

    /**
     * Create an instance of {@link Wizard }
     * 
     */
    public Wizard createWizard() {
        return new Wizard();
    }

    /**
     * Create an instance of {@link ArrayOfSteptype }
     * 
     */
    public ArrayOfSteptype createArrayOfSteptype() {
        return new ArrayOfSteptype();
    }

    /**
     * Create an instance of {@link ImplicitWizardMetadata }
     * 
     */
    public ImplicitWizardMetadata createImplicitWizardMetadata() {
        return new ImplicitWizardMetadata();
    }

    /**
     * Create an instance of {@link ListControl }
     * 
     */
    public ListControl createListControl() {
        return new ListControl();
    }

    /**
     * Create an instance of {@link StringControl }
     * 
     */
    public StringControl createStringControl() {
        return new StringControl();
    }

    /**
     * Create an instance of {@link AndTrigger }
     * 
     */
    public AndTrigger createAndTrigger() {
        return new AndTrigger();
    }

    /**
     * Create an instance of {@link ArrayOfImplicitWizardMetadata }
     * 
     */
    public ArrayOfImplicitWizardMetadata createArrayOfImplicitWizardMetadata() {
        return new ArrayOfImplicitWizardMetadata();
    }

    /**
     * Create an instance of {@link XPathDataSource }
     * 
     */
    public XPathDataSource createXPathDataSource() {
        return new XPathDataSource();
    }

    /**
     * Create an instance of {@link EmptyTrigger }
     * 
     */
    public EmptyTrigger createEmptyTrigger() {
        return new EmptyTrigger();
    }

    /**
     * Create an instance of {@link LabelControl }
     * 
     */
    public LabelControl createLabelControl() {
        return new LabelControl();
    }

    /**
     * Create an instance of {@link NotTrigger }
     * 
     */
    public NotTrigger createNotTrigger() {
        return new NotTrigger();
    }

    /**
     * Create an instance of {@link GreaterOrEqualThanComparisonTrigger }
     * 
     */
    public GreaterOrEqualThanComparisonTrigger createGreaterOrEqualThanComparisonTrigger() {
        return new GreaterOrEqualThanComparisonTrigger();
    }

    /**
     * Create an instance of {@link ImageFileControl }
     * 
     */
    public ImageFileControl createImageFileControl() {
        return new ImageFileControl();
    }

    /**
     * Create an instance of {@link Steptype }
     * 
     */
    public Steptype createSteptype() {
        return new Steptype();
    }

    /**
     * Create an instance of {@link CheckboxControl }
     * 
     */
    public CheckboxControl createCheckboxControl() {
        return new CheckboxControl();
    }

    /**
     * Create an instance of {@link ExplicitWizardMetadata }
     * 
     */
    public ExplicitWizardMetadata createExplicitWizardMetadata() {
        return new ExplicitWizardMetadata();
    }

    /**
     * Create an instance of {@link MultiControl }
     * 
     */
    public MultiControl createMultiControl() {
        return new MultiControl();
    }

    /**
     * Create an instance of {@link LessThanComparisonTrigger }
     * 
     */
    public LessThanComparisonTrigger createLessThanComparisonTrigger() {
        return new LessThanComparisonTrigger();
    }

    /**
     * Create an instance of {@link TextControl }
     * 
     */
    public TextControl createTextControl() {
        return new TextControl();
    }

    /**
     * Create an instance of {@link MetadataTriggerValue }
     * 
     */
    public MetadataTriggerValue createMetadataTriggerValue() {
        return new MetadataTriggerValue();
    }

    /**
     * Create an instance of {@link OrTrigger }
     * 
     */
    public OrTrigger createOrTrigger() {
        return new OrTrigger();
    }

    /**
     * Create an instance of {@link ControlTriggerValue }
     * 
     */
    public ControlTriggerValue createControlTriggerValue() {
        return new ControlTriggerValue();
    }

    /**
     * Create an instance of {@link ArrayOfListItem }
     * 
     */
    public ArrayOfListItem createArrayOfListItem() {
        return new ArrayOfListItem();
    }

    /**
     * Create an instance of {@link EmailControl }
     * 
     */
    public EmailControl createEmailControl() {
        return new EmailControl();
    }

    /**
     * Create an instance of {@link FileNameControl }
     * 
     */
    public FileNameControl createFileNameControl() {
        return new FileNameControl();
    }

    /**
     * Create an instance of {@link RegexTrigger }
     * 
     */
    public RegexTrigger createRegexTrigger() {
        return new RegexTrigger();
    }

    /**
     * Create an instance of {@link GreaterThanComparisonTrigger }
     * 
     */
    public GreaterThanComparisonTrigger createGreaterThanComparisonTrigger() {
        return new GreaterThanComparisonTrigger();
    }

    /**
     * Create an instance of {@link ConstTriggerValue }
     * 
     */
    public ConstTriggerValue createConstTriggerValue() {
        return new ConstTriggerValue();
    }

    /**
     * Create an instance of {@link ArrayOfChoice2 }
     * 
     */
    public ArrayOfChoice2 createArrayOfChoice2() {
        return new ArrayOfChoice2();
    }

    /**
     * Create an instance of {@link ArrayOfChoice1 }
     * 
     */
    public ArrayOfChoice1 createArrayOfChoice1() {
        return new ArrayOfChoice1();
    }

    /**
     * Create an instance of {@link RadioControl }
     * 
     */
    public RadioControl createRadioControl() {
        return new RadioControl();
    }

    /**
     * Create an instance of {@link AttachmentFileControl }
     * 
     */
    public AttachmentFileControl createAttachmentFileControl() {
        return new AttachmentFileControl();
    }

    /**
     * Create an instance of {@link FileControl }
     * 
     */
    public FileControl createFileControl() {
        return new FileControl();
    }

    /**
     * Create an instance of {@link LessOrEqualThanComparisonTrigger }
     * 
     */
    public LessOrEqualThanComparisonTrigger createLessOrEqualThanComparisonTrigger() {
        return new LessOrEqualThanComparisonTrigger();
    }

    /**
     * Create an instance of {@link DateControl }
     * 
     */
    public DateControl createDateControl() {
        return new DateControl();
    }

    /**
     * Create an instance of {@link EqualComparisonTrigger }
     * 
     */
    public EqualComparisonTrigger createEqualComparisonTrigger() {
        return new EqualComparisonTrigger();
    }

    /**
     * Create an instance of {@link DifferentComparisonTrigger }
     * 
     */
    public DifferentComparisonTrigger createDifferentComparisonTrigger() {
        return new DifferentComparisonTrigger();
    }

    /**
     * Create an instance of {@link ListItem }
     * 
     */
    public ListItem createListItem() {
        return new ListItem();
    }

    /**
     * Create an instance of {@link NumberControl }
     * 
     */
    public NumberControl createNumberControl() {
        return new NumberControl();
    }

    /**
     * Create an instance of {@link ArrayOfWizardCondition.Condition }
     * 
     */
    public ArrayOfWizardCondition.Condition createArrayOfWizardConditionCondition() {
        return new ArrayOfWizardCondition.Condition();
    }

    /**
     * Create an instance of {@link ArrayOfWizardAdvancedRule.AdvancedRule }
     * 
     */
    public ArrayOfWizardAdvancedRule.AdvancedRule createArrayOfWizardAdvancedRuleAdvancedRule() {
        return new ArrayOfWizardAdvancedRule.AdvancedRule();
    }

    /**
     * Create an instance of {@link ArrayOfWizardQuestion.Question }
     * 
     */
    public ArrayOfWizardQuestion.Question createArrayOfWizardQuestionQuestion() {
        return new ArrayOfWizardQuestion.Question();
    }

}
