//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.04 at 06:05:10 PM CET 
//


package nl.thedocumentwizard.wizardconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnaryTrigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnaryTrigger">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}Trigger">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Const" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ConstTriggerValue" minOccurs="0"/>
 *           &lt;element name="Control" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}ControlTriggerValue" minOccurs="0"/>
 *           &lt;element name="Metadata" type="{http://www.thedocumentwizard.nl/wizardconfiguration/2.0}MetadataTriggerValue" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnaryTrigger", propOrder = {
    "_const",
    "control",
    "metadata"
})
@XmlSeeAlso({
    EmptyTrigger.class,
    RegexTrigger.class
})
public abstract class UnaryTrigger
    extends Trigger
{

    @XmlElement(name = "Const")
    protected ConstTriggerValue _const;
    @XmlElement(name = "Control")
    protected ControlTriggerValue control;
    @XmlElement(name = "Metadata")
    protected MetadataTriggerValue metadata;

    /**
     * Gets the value of the const property.
     * 
     * @return
     *     possible object is
     *     {@link ConstTriggerValue }
     *     
     */
    public ConstTriggerValue getConst() {
        return _const;
    }

    /**
     * Sets the value of the const property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstTriggerValue }
     *     
     */
    public void setConst(ConstTriggerValue value) {
        this._const = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link ControlTriggerValue }
     *     
     */
    public ControlTriggerValue getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlTriggerValue }
     *     
     */
    public void setControl(ControlTriggerValue value) {
        this.control = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataTriggerValue }
     *     
     */
    public MetadataTriggerValue getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataTriggerValue }
     *     
     */
    public void setMetadata(MetadataTriggerValue value) {
        this.metadata = value;
    }

}
